### ISSUE TITLE
Access Denied to photos

### ISSUE THREAD

**Issue by gateway** [ParsePlatform/parse-dashboard#101]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ x] You're running version >=2.1.4 of Parse Server.

- [ x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
parse dashboard running on osx
parse server running on a heroku which had data migrated over

#### Steps to reproduce
from an existing migration with photos, click on the photo in the browser can you get

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>E789314D2CDFAF82</RequestId>
<HostId>
3fVSHoF49jP3JwBL3YKZfKE58SnRQzUmgug3zOBke1wd3p45bLpjZWgjJRkL9+wHyCFoab1B9vc=
</HostId>
</Error> 

```

**Comment by drew-gross** [comment]
We made some updates to Parse Server that should have fixed this. Please try updating your Parse Server version and open a new issue if you still see this error.

**Comment by gateway** [comment]
I have to reopen this, Im seeing this again from the parse dashboard.. clicking on a photo in the dashboard.. any thoughts.. its kinda important because we tore apart all our xcode queries we where doing and I thought it might be the photo.. since I saw a 403 returned in the console.

**Comment by drew-gross** [comment]
Is the photo accessible from your app? Also is this a photo that was created by Parse Server, or by Parse.com? cc @skinp who knows more about files.

**Comment by gateway** [comment]
App works since we are still running on parse.com , doing some migration testing where I set up parse server, dashboard and migrated data to mlab.. cant access the photos from the new setup, but parse.com works.

**Comment by skinp** [comment]
@gateway the error message looks like it comes from S3. Are you using the S3 adapter?

This looks pretty much like an S3 permission problem. Can you query the same file without using curl?

**Comment by gateway** [comment]
@skinp no curl used, this is a part of a few issues posted, it started when I went to pretest migration of our app to parse server, parse dashboard, mlab as the db..

Then connecting via our iOS app stuff started to break, and we traced it down to 403 which of course was the images where not able to be accessed causing the app to crash.

I do have fileKey and filesAdpator set up for s3, but its my understanding any new images added go to s3 instead and any legacy stuff from the migration still is in parse.com s3 bucket until they provide a tool to migrate.

**Comment by ideastouch** [comment]
Hi guys,
I think that this issue is not related to the migration.
In my case the scenario is:
- One DataBase migrated to mLab (Heroku Addons)
- One Heroku app running Parse-Server and Parse-Dashboard.
- One Heroku app running Express server which is connected to the already migrated Parse-Server.
- One iOS app connected to the already migrated Parse-Server.
- Parse.com app still running with his dashboard as well.

Now let say:
1. **Photos A** where created before migration.
2. **Photos B** where created after migration.

The result is that **Photos B** are pointing to a different directory in http://files.parsetfss.com/ than **Photos A**.

Some how, iOS app shows both kind of photos but the Express client doesn't, neither both Dashboards. My guess is that there is an issue in JavaScript Api, should be when is getting the File Object 
from a ParseObject. Make sense?

Did Anyone thought some workaround or have one already?

Best,
Gus

**Comment by drew-gross** [comment]
This should be fixed in the latest version of Parse Server.

**Comment by yifli** [comment]
I'm still having the same issue. I'm running Paser server 2.2.18 on localhost. 
My app works fine with parse.com.

Any idea how to fix it?

Thanks,
Yifei

**Comment by kartheeknagasuri** [comment]
@yifli  i am also facing same issue.. were you able to resolve the issue?

**Comment by kumarpranav** [comment]
@drew-gross I am using latest parse server version but still facing Access Denied. Even on accessing files on parsetfss.com too. This is my url that i am trying to access

http://files.parse.com/a25bce39-030c-46e8-8f41-15cd0c14f60b/b94b0d1d-a73a-4516-a244-005d65be552c-thumbnail.jpg

**Comment by hamzazar** [comment]
@drew-gross Same here,  we use the latest version of parse server in AWS Elastic Beanstalk. The files are on an AWS S3. The news files are displayed on both web app and dashboard without errors but when tring to get the images of data migrated from parse.com we get the Access Denied XML page.

**Comment by kanersan** [comment]
@drew-gross I'm also having the same problem right now.
Parse-server version: 2.3.1
