### ISSUE TITLE
Can we Install the dashboard on Heroku,? 

### ISSUE THREAD

**Issue by wallydsyh** [ParsePlatform/parse-dashboard#159]
Hello,

I was wondering if we can install the Dashboard on heroku.

I just tried and got this error 
![image](https://cloud.githubusercontent.com/assets/17909907/13854648/d893f2b0-ec6c-11e5-83cd-e7b3b31cffa3.png)
if you have any idea. please

Thanks you.

**Comment by yguy08** [comment]
Hey @wallydsyh,

Take a look here: [https://github.com/ParsePlatform/parse-dashboard#deploying-the-dashboard](url)

The section says, "If you are deploying the dashboard, then localhost urls will not work."

Are you still using localhost urls?

**Comment by wallydsyh** [comment]
Thanks you for the link . but it seems like its not available anymore.
yes, my dashboard is running on  localhost perfectly, but i wanted to know i could deploy iton heroku as well as did with the Parse Server.

**Comment by yguy08** [comment]
@wallydsyh my fault, fixed it. Go ahead and try it again. That section should point you in the right direction. 

If it works on localhost perfectly, that's great! 

If you want to deploy the dashboard _anywhere_ you will have to make some changes to your URLs. 

Did you make changes to your URLs or are you still using localhost URLs in the code you deployed to Heroku when you got the Application Error?

**Comment by wallydsyh** [comment]
Actually when i deployed the app on heroku i changed the URL

here is how it looks like 
"apps": [
  {
	 "serverURL": "http://sometihing.herokuapp.com/parse",
      "appId": "AppId",
      "masterKey": "masterKey",
      "appName": "Appname"
}
]

the Url is the Url in which  i install the Parse Server.

i don't really know which URL i should pass in the "serverUrl"
do you have any idea  please ?

**Comment by benaneesh** [comment]
@wallydsyh are you still getting the heroku application error? 

I just tried this with these config:
```json
{
  "apps": [
    {
      "serverURL": "https://your-app.herokuapp.com/parse",
      "appId": "your_app_id",
      "masterKey": "your_master_key",
      "javascriptKey": "your_javascript_key",
      "restKey": "yor_rest_key",
      "appName": "cover-migration"
    }
  ],
  "users": [
    {
      "user":"admin@example.com",
      "pass":"password"
    }
  ]
}
```


but there seems to be another error now, an empty page with this error:

![screen shot 2016-03-17 at 12 51 47 pm](https://cloud.githubusercontent.com/assets/1724896/13859125/12cfc45a-ec3f-11e5-86f9-4faecd0e8458.png)

**Comment by wallydsyh** [comment]
Excatly, i have the same thing , a blank page too. 

you know what is causing it ?

**Comment by drew-gross** [comment]
We've pushed a new version to `npm` and recommend using that instead of the old installation method. The `npm` package shouldn't have that issue, so I recommend you try that one.

**Comment by Dima564** [comment]
@drew-gross I'm still getting "Unexpected token <" when I deploy to Heroku

**Comment by drew-gross** [comment]
Could you open a new issue describing how you are installing and deploying?

**Comment by flyingmate** [comment]
I had the same problem, and found bundle.js was empty (ignored by .gitignore).
So I deleted /bundles line in .gitignore file, there was some progress.
Then got 'Parse Dashboard can only be remotely accessed via HTTPS' error page (better than blank page), so set PARSE_DASHBOARD_ALLOW_INSECURE_HTTP to 1 on heroku env setting.
It's now working finally

**Comment by Apptation** [comment]
@flyingmate I tried deleting /bundles line in .gitignore file, but this didn't solve the problem for me. I still get the same blank page with "Unexpected token <" error in the source.

Did you change anything else to possibly fix this issue?

@drew-gross would you like me to open up a issue for this? I will include all the steps to reproduce. Thanks

**Comment by flyingmate** [comment]
@Apptation you need to check if the asset files under pubilc/bundles folder are deploying to heroku correctly. [Unexpected token <] issue must be caused by the absence of asset files

**Comment by Apptation** [comment]
@flyingmate there is no public/bundles folder in the repo. Do I misunderstand or am I missing something?
Thx

**Comment by flyingmate** [comment]
@Apptation  you should 'npm install', then you will have bundles folder under Parse-Dashboard/public. And you need to set your apps on parse-dashboard-config.json file before deploying

**Comment by Apptation** [comment]
@flyingmate That fixed the obvious problem. Running npm install locally, and then pushing to Heroku

Thanks! Running Parse Dashboard smoothly on Heroku now.

**Comment by flyingmate** [comment]
@Apptation :)

**Comment by andrewcbancroft** [comment]
I really appreciate this thread, but it took me far too long to come across it before I finally got my Parse Dashboard deployed and working.  To keep track of it for myself, I created a walkthrough at https://www.andrewcbancroft.com/2016/04/17/deploying-parse-dashboard/ .   

I would be interested in contributing this walkthrough or something like it to the docs of this project to help others out if that'd be well-received.  I just created it on my blog so that I, myself could remember the steps.  In any case, I'm hoping the post sheds a little more light on how to fix the "Unexpected token <" error.

**Comment by drew-gross** [comment]
Looks good to me. A PR adding the link to the README would definitely be accepted! You might be interested to know that we also have a `npm` package now that might simplify your deployment flow.

**Comment by andrewcbancroft** [comment]
Thanks Drew - I'll work something up!  I don't mind extracting the content from my blog and embedding it directly into the README somehow if that's more appropriate.

The `npm` package approach sounds great!  I'm assuming it'd be a simple `npm install` for the package, and then the deployment would be the output of that, plus the needed config updates?

**Comment by drew-gross** [comment]
The `npm` package include command line tool to serve the app or mount on an existing express app. Setting up Heroku to run the command line tool is probably the way to go, with a command line flag pointing to the config file. Heroku isn't really set up to be used that way, so you may have to come up with something that deals with that.

**Comment by rizdem** [comment]
Hi Does anybody know how to help with my issue, so i got my dashboard loaded to heroic where i was displayed with the  'Parse Dashboard can only be remotely accessed via HTTPS' i then went in to my config variables on heroku and added the PARSE_DASHBOARD_ALLOW_INSECURE_HTTP now all i get is my app saying 'unable to connect to server' when i open the web inspector it says that its being blocked. 'was not allowed to display insecure content from' then my parse server url can anybody help me. its my last hurdle.

Thanks in advance

**Comment by Somkid2555** [comment]
http://android-kill-the-what.blogspot.com/2016/05/heroku-deploy-parse-dashboard-step.html

**Comment by johnantoni** [comment]
managed to get it up on heroku,

this is the best working tutorial i've found:

for heroku, you will need to set the config variable even if you use heroku's https path

`PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=1`

plus --allowInsecureHTTP has no effect on heroku, you can drop that. guessing it's different with an actual docker setup.

**Comment by joevo2** [comment]
I'm using the parse dashboard as a middleware with my parse server on heroku. adding the PARSE_DASHBOARD_ALLOW_INSECURE_HTTP doesn't seems to work. Any idea on how to make it work? i tried to run the parse dashboard locally to connect to it doesn't work as well. but of course running the entire parse server + parse dashboard middleware works locally

**Comment by markmssd** [comment]
Instead of pushing the ```Parse-Dashboard/parse-dashboard-config.json``` file to Github, I'm trying to deploy it with ```npm run build && npm start```, and setting environment variables in Heroku's settings. I've also set ```PARSE_DASHBOARD_ALLOW_INSECURE_HTTP``` to ```1```... but no luck.

Variables set in Heroku's settings:
```PARSE_DASHBOARD_APP_ID```
```PARSE_DASHBOARD_APP_NAME```
```PARSE_DASHBOARD_MASTER_KEY```
```PARSE_DASHBOARD_SERVER_URL```
```PARSE_DASHBOARD_USER_ID```
```PARSE_DASHBOARD_USER_PASSWORD```
```PARSE_DASHBOARD_ALLOW_INSECURE_HTTP```

Any pointers? I'm sure many people would prefer this method, rather than pushing secret masterKey/passwords to Github.

Thanks in advance!

**Comment by krzykz** [comment]
@markmssd 
So, i have found a solution for heroku's bundle generation, the problem is this variable (env) NPM_CONFIG_PRODUCTION, if you set it to false, it will then install the devDependencies and subsequently run webpack, which will generate the bundle files.

**Comment by markmssd** [comment]
@krzykz 
Hey thanks for your suggestion! I will give it a try when I have time. For now, I used a workaround.
I used ```heroku run bash``` to access my Heroku repo, and I modified the ```parse-dashboard-config.json``` file directly through here. As for the bundle files problem, I installed Parse-Dashboard through as an ```npm``` (through ```package.json```).

P.S: instead of removing the procfile, you can modify the commands to use inside it. Instead of the default command telling it to use the config file, you can change it to ```npm start```. ```npm install``` is already triggered automatically by Heroku, so no need to put it before npm start.

**Comment by harryworld** [comment]
Is it still secure on Heroku after using `PARSE_DASHBOARD_ALLOW_INSECURE_HTTP`? I checked the network audit on Chrome, seems all the requests are still https, with `POST` handling the login

**Comment by Tapaniya25** [comment]
I followed these steps when i try to open [this link](https://testapp.herokuapp.com/parse). Browser redirects me to [here] (https://testapp.herokuapp.com/apps/testapp/browser). Not showing parse database.
