### ISSUE TITLE
While Uploading file to Amazon S3 storage Parse dashboard passes content type "text/plain" for all type of files.

### ISSUE THREAD

**Issue by rvparekh** [ParsePlatform/parse-dashboard#384]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [X] You're running version >=2.1.4 of Parse Server.

- [X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

Amazon AWS ElastinBenstalk runnig nodejs version 4.x.x
Parse Dashboard + Parse server + Amazon S3 File Storage

#### Steps to reproduce
1) Click on Upload file on Filetype column
2) Select Pdf and press ok.
3) when file is uploaded check the post request header on Developer console and also S3 storage pdf file content type is set as "text/plain"
![2016-05-30_1755](https://cloud.githubusercontent.com/assets/4578566/15649524/cb0d9a12-268f-11e6-8a34-22ee3ab7b52f.png)

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by rvparekh** [comment]
@daaku Hi can anybody help me with this?

**Comment by drew-gross** [comment]
This issue should be fixed in the newest version of Parse Server (2.2.11)

**Comment by rvparekh** [comment]
This issue still exists.

I have tested today by uploading pdf file and on amazon s3 metadata it shows text/plain.

**Comment by drew-gross** [comment]
Can you reopen the bug on the parse server repo and include the server logs?

**Comment by lucoceano** [comment]
I still have the problem in here when trying to upload a pdf file.

#### Environment Setup

Parse Dashboard: 1.0.19
Parse Server: 2.2.24
Node: 4.4.4
Parse Dashboard + Parse server + Amazon S3 File Storage
