### ISSUE TITLE
Blank screen with nginx reverse proxy

### ISSUE THREAD

**Issue by fnberta** [ParsePlatform/parse-dashboard#64]
I'm accessing nginx on my server via an SSL connection and passing the request to the dashboard express app via a reverse proxy. The title of the tab gets named "Parse Dashboard" but the screen is completely blank.

My dashboard config is:
```
{
  "apps": [
    {
      "serverURL": "https://SERVER_IP/api/data",
      "appId": "XXXXX",
      "masterKey": "XXXX",
      "appName": "APPNAME"
    }
  ],
  "users": [
    {
      "user":"user1",
      "pass":"XXXXX"
    },
    {
      "user":"user2",
      "pass":"XXXXX"
    }
  ]
}
```

And the nginx proxy config is:
```
location /dashboard {
		proxy_pass http://127.0.0.1:4040;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
	}
```

I'm using a similar configuration for the express app that runs parse-server and that works flawlessly. Any idea what could be going wrong here? If I run the dashboard locally it works perfectly fine.

**Comment by drew-gross** [comment]
Could you check if your server is responding with the correct files? The dashboard only makes about 5 requests the dashboard app. Also, the dashboard requires the connection to the dashboard be HTTPS (to prevent accidental leakage of the master keys) which may be causing issues. (although I would expect an error message in that case, not a blank page)

**Comment by Cliffordwh** [comment]
Identical problem my side. Have HTTPS server and still blank. Title tho says "Parse Dashboard"

**Comment by fnberta** [comment]
A GET request to https://SERVER_IP/dasboard returns:

```
<!DOCTYPE html>
<html>
    <title>Parse Dashboard</title>
    <body>
        <div id="browser_mount"></div>
        <script src="/bundles/dashboard.bundle.js"></script>
  
    </body>
</html>
```
Which is correct I guess? But /bundles/dashboard.bundle.js is not correctly served because /bundles is not piped to the express app but instead handled by nginx, which of course cannot find the file. Changing the path in the index.html to:
````
/dashboard/bundles/dashboard.bundle.js
````
results in the dasboard trying to load but failing with a "404, Oh no, we can't find that page!" error. So it seems like the /dashboard prefix would be needed for other files as well. Can I set this somewhere "globally"?

Btw, if I pipe / to the express app, the dashboard works perfectly. But this of course conflicts with other content I would like to serve on /.

**Comment by drew-gross** [comment]
the 404 is because there is no `/dashboard` route. The routes are the same as on `dashboard.parse.com`. Try `/apps`.

**Comment by Cliffordwh** [comment]
@fnberta You manage to find a fix for this?

**Comment by guitcastro** [comment]
I am also having this issue as well in the Heroku.

**Comment by gfosco** [comment]
I think we can address this.  The dashboard is using / to start its paths, so it can only currently be hosted on the root of a URL.  Will work on a PR to use relative paths.

**Comment by vegidio** [comment]
+1

**Comment by felipemobile** [comment]
Same issue on an EC2 nano instance and OS X El Capitan 10.11.3 both running Node.js 4.3.2

**Comment by fnberta** [comment]
@Cliffordwh No, for the moment I am directly accessing the Express app via SSL. But looking forward to switch back to the reverse proxy when the relative paths land!

**Comment by andremilk** [comment]
I am having the same issue. Actually even if try locally (then no https and bypassing the nginx proxy) I get the Blank page with 


    <!DOCTYPE html>
        <html>
           <title>Parse Dashboard</title>
           <body>
               <div id="browser_mount"></div>
               <script src="/bundles/dashboard.bundle.js"></script>
          </body>
      </html>

**Comment by peterdotjs** [comment]
@andremilk for your local issue - can you post more info in #120?

**Comment by Cliffordwh** [comment]
any news on this? or fix to get parse-dashboard to run off a sub? and not the root /

thanks

**Comment by joeyslack** [comment]
Hey there,

It's an issue with npm instal --production. Unfortunately, this app has not been tested with production flag, so your app will not work without some changes.

You'll want to modify the .gitignore file, and remove the following:

bundles/
PIG/bundles/
Parse-Dashboard/public/bundles/
Parse-Dashboard/parse-dashboard-config.json

Then, when you run: `npm install` on your dev, check in the files it generates to your local repo, then deploy those files to your production.

**Comment by drew-gross** [comment]
@joeyslack the --production flag is left over from our internal build process for running dashboard.parse.com. For just using the dashboard, I recommend installing from `npm`. For developing the dashboard, I recommend cloning the repo and using `npm run dashboard`.

**Comment by joeyslack** [comment]
Cool thanks. I'll send a PR then with recommendations for deploys working
with hosting (AWS)

**Comment by Cliffordwh** [comment]
I don't see this solving the issue. All the files are there on the NPM run, just can not run via  a sub directory only on root domain ( / ).  We need relative paths or set a prefix globally for the path.

**Comment by joeyslack** [comment]
@Cliffordwh I'm personally missing files on npm run, after a npm install --production, you have a /bundles folder after doing that?

**Comment by devgeek27** [comment]
Blank screen with Parse Dashboard title issue is happening to me as well. I have deployed Dashboard to Elastic Beanstalk and having the blank screen there. The Dashboard works locally though. The problem is with loading <script src="/bundles/dashboard.bundle.js"></script> file. Does anyone know how to fix that?

**Comment by geraugu** [comment]
I have the same cenario. Bundles are missing. How can I fix this?

**Comment by Cliffordwh** [comment]
@gfosco any luck on this to allow relative paths?

**Comment by joeyslack** [comment]
Hey guys, read my comment above on how to fix it for remote hosts (like elastic beanstalk).

You'll want to first run `npm install` locally, and then modify your .gitignore file, to remove the /bundles (and other) paths. No idea why someone would ever check in those gitignore changes.

Then, when you do your commit and deploy, the bundle will be available.

Secondarily, if you are using AWS Beanstalk, you'll have to set up a static path for /bundle -> to point to the /public folder.

**Comment by devgeek27** [comment]
@joeyslack Thanks mate. I'll give it a try today.

**Comment by iStopped** [comment]
+1

**Comment by drew-gross** [comment]
This should be fixed now.

**Comment by thuantran** [comment]
I ran an npm update to update to 1.0.8 but it still doesn't work for me behind nginx.
Here's my config.json:
```json
{
  "apps": [
    {
      "allowInsecureHTTP": 1,
      "serverURL": "url",
      "appId": "appid",
      "masterKey": "masterkey",
      "appName": "appname"
    }
  ],
  "users": [
    {
      "user": "user",
      "pass": "pass"
    }
  ]
}
```
And here's my nginx config
```
location /admin/ {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-NginX-Proxy true;
    proxy_pass http://localhost:4040/;
    proxy_ssl_session_reuse off;
    proxy_set_header Host $http_host;
    proxy_redirect off;
  }
```
The nginx virtual server config also has HTTPS termination as it is also the reverse proxy for parse-server and that's working. What's wrong? If you need other information, please do tell.

Best regards,
Thuan

**Comment by vegidio** [comment]
I'm also having the same problem described by @thuantran

**Comment by drew-gross** [comment]
I'm actually not particularly familiar with nginx. @gfosco might be able to help more, or you could ask a question on Stack Overflow or Server Fault. I do know that the relative paths issue originally brought up has been fixed, so it sounds like you might be seeing a different issue.

**Comment by vegidio** [comment]
Hi,

Basically what I want to do is to have Parse Server accessible through the URL: `my-parse-domain.com`, but when the user type `my-parse-domain.com/dashboard` it will show the Parse Dashboard. Sadly it's not working yet (I installed the latest version 5 minutes ago) and I used the same nginx configuration used by @thuantran.

The problem is: when I access `my-parse-domain-com/dashboard` it's still showing a blank screen. I looked at the page source code and I found this:

```
<!DOCTYPE html>
<html>
  <title>Parse Dashboard</title>
  <body>
    <div id="browser_mount"></div>
    <script src="/bundles/dashboard.bundle.js"></script>
  </body>
</html>
```

The script tag is starting with a slash "/". It means that it will look for the file `/bundles/dashboard.bundle.js` in the domain root (`my-parse-domain-com/bundles/dashboard.bundle.js`), but this is wrong, it's getting a 404 error.

The correct behavior is to have script tag start without "/", like this `bundles/dashboard.bundle.js` so the Parse Dashboard will look for the `dashboard.bundle.js` file in the relative location. In my case: `my-parse-domain-com**/dashboard/**bundles/dashboard.bundle.js`

I hope this helped to clarify the problem :)

Thanks.

**Comment by thuantran** [comment]
Finally manage to fix it, the problem is try_files $uri $uri/ =404; in location / causing the problem, remove that and it works.

**Comment by cyring** [comment]
@thuantran : may you please post your successful configurations file ( nginx.conf ) ?

**Comment by andrew8712** [comment]
This issue still persists for me. Any other workarounds?

**Comment by wassup-** [comment]
For people here who've (like me) **tried all of the above but are still getting served a blank page** (title but no content): please check the page's sourcecode to make sure it's not empty.

If it's not empty, follow the link to the included javascript **login.bundle.js** or **dashboard.bundle.js** file. If your browser gives you a **404** (file not found), make sure NginX's `sendfile` is `off`. Apparently this is important when NginX is acting as a reverse proxy.

This solved it for me, *YMMV*. More info about sendfile here: https://t37.net/optimisations-nginx-bien-comprendre-sendfile-tcp-nodelay-et-tcp-nopush.html

**Comment by nexriz** [comment]
Umm.. Had the same issue when i tried to access my dashboard with https://xxxxx.com/dashboard. Used nginx proxy_pass (https to http), and got the blank screen but with net::ERR_CONTENT_LENGTH_MISMATCH in console.
Strange part was that it worked when i tried to access it locally. (https://localhost/dashboard)

Looked around a bit and found that
NGINX needs to run as a user that have permission to static files. (caching them or something, idk) 
So i tried to run sudo nginx and it worked. (but dont run sudo in production)

other solution -
adding this to nginx.conf

user nobody;

**Comment by shodanx2** [comment]
Hi,

This issue is google top link for "nginx redirect just black screen"

And to anyone that ends up here, what you most likely need to do is just 
change your http redirection code

![image](https://user-images.githubusercontent.com/10621885/200159745-20213ebf-b84e-4d99-877f-7a1c295ac0f5.png)
